language: python
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
install:
  - python3 -m virtualenv venv
  - . venv/bin/activate
  - pip install -r requirements.txt
script:
  - . venv/bin/activate
  - pylint src --rcfile=setup.cfg